apiVersion: v1
kind: Service
metadata:
  name: devops-awkwob-service
  labels:
    app: devops-awkwob-project
spec:
  selector:
    app: devops-awkwob-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
