apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devops-awkwob-deployment
spec:
  selector:
    matchLabels:
      app: devops-awkwob-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: devops-awkwob-project
    spec:
      containers:
      - name: devops-awkwob-project
        image: thunder005/simple-devops-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
